// Verifier #14 INDEPENDENT mutation battery.
// Written from scratch; deliberately does NOT run qa/verification/proposed/v13_mutation_proof.mjs.
//
// Two kinds of mutation, and the second is the point:
//   COVERAGE  — remove/disable the guard. A committed case MUST fail.
//   LIMIT     — over-broaden the guard (drop an anchor, widen a class, remove a negation,
//               loosen an equality). A committed CONTRACT case MUST fail, or the guard's
//               NARROWNESS is unobserved — the exact vacuous-guard class this project has
//               shipped ten times.
export const MUTATIONS = [
  // ================= G1: FIX-3b INTERROGATIVE_LEAD question belt =================
  { id: 'G1.cov.remove', guard: 'G1 FIX-3b', kind: 'COVERAGE',
    what: 'delete the completion-word question belt entirely',
    from: `          if (COMPLETION_WORD.test(q) && !INTERROGATIVE_LEAD.test(q)) return null;`,
    to:   `          if (false) return null;` },
  { id: 'G1.lim.dropNegation', guard: 'G1 FIX-3b', kind: 'LIMIT',
    what: 'drop the !INTERROGATIVE_LEAD negation (belt becomes the run11 blanket test)',
    from: `          if (COMPLETION_WORD.test(q) && !INTERROGATIVE_LEAD.test(q)) return null;`,
    to:   `          if (COMPLETION_WORD.test(q)) return null;` },
  { id: 'G1.lim.dropStartAnchor', guard: 'G1 FIX-3b', kind: 'LIMIT',
    what: 'remove INTERROGATIVE_LEAD\'s ^ anchor (an interrogative word ANYWHERE counts as a lead)',
    from: `const INTERROGATIVE_LEAD = /^(please\\s+)?(who|`,
    to:   `const INTERROGATIVE_LEAD = /(please\\s+)?(who|` },
  { id: 'G1.lim.dropWordBoundary', guard: 'G1 FIX-3b', kind: 'LIMIT',
    what: 'remove INTERROGATIVE_LEAD\'s trailing \\b (prefix words like "Whoever"/"Ismail" count as leads)',
    from: `|have|has|had|if)\\b/i;`,
    to:   `|have|has|had|if)/i;` },
  { id: 'G1.lim.addTheAlternative', guard: 'G1 FIX-3b', kind: 'LIMIT',
    what: 'add a non-interrogative alternative ("the") to INTERROGATIVE_LEAD',
    from: `const INTERROGATIVE_LEAD = /^(please\\s+)?(who|`,
    to:   `const INTERROGATIVE_LEAD = /^(please\\s+)?(the|who|` },

  // ================= G2: D100 label corroboration =================
  { id: 'G2.cov.noCorroboration', guard: 'G2 D100', kind: 'COVERAGE',
    what: 'accept any safeOptionLabel without corroborating it against the canonical read',
    from: `              o.label = (safeLabel && (!COMPLETION_WORD.test(safeLabel) || bare(safeLabel) === bare(derivedLabel)))\r\n                ? safeLabel\r\n                : derivedLabel;`,
    to:   `              o.label = safeLabel ? safeLabel : derivedLabel;` },
  { id: 'G2.lim.alwaysDerived', guard: 'G2 D100', kind: 'LIMIT',
    what: 'over-broaden: always replace the label with the derived canonical reference',
    from: `              o.label = (safeLabel && (!COMPLETION_WORD.test(safeLabel) || bare(safeLabel) === bare(derivedLabel)))\r\n                ? safeLabel\r\n                : derivedLabel;`,
    to:   `              o.label = derivedLabel;` },
  { id: 'G2.lim.noBareNormalise', guard: 'G2 D100', kind: 'LIMIT',
    what: 'compare raw instead of bare() (a canonical name safeDisplayLabel QUOTED no longer corroborates)',
    from: `bare(safeLabel) === bare(derivedLabel)`,
    to:   `safeLabel === derivedLabel` },
  { id: 'G2.lim.substringCorroboration', guard: 'G2 D100', kind: 'LIMIT',
    what: 'loosen equality to containment (a fabricated label that is a SUBSTRING of the canonical name is corroborated)',
    from: `bare(safeLabel) === bare(derivedLabel)`,
    to:   `bare(derivedLabel).includes(bare(safeLabel))` },
  { id: 'G2.lim.corroborateAnyOption', guard: 'G2 D100', kind: 'LIMIT',
    what: 'corroborate against ANY canonical name in the read, not the one belonging to this id',
    from: `bare(safeLabel) === bare(derivedLabel)`,
    to:   `paObj.options.some((oo) => oo && typeof oo.id === 'string' && bare(safeLabel) === bare(displayName(typeof oo.entityType === 'string' ? oo.entityType : 'record', oo.id)))` },

  // ================= G3: safeOptionLabel's completion sub-guards (D78/D86/D91/D101) =====
  { id: 'G3.cov.narrowAdjectival', guard: 'G3 D101', kind: 'COVERAGE',
    what: 'narrow ADJECTIVAL_COMPLETION to closed only (a real "Completed Works Ltd" must lose its name)',
    from: `const ADJECTIVAL_COMPLETION = /^(closed|completed|restored)$/i;`,
    to:   `const ADJECTIVAL_COMPLETION = /^(closed)$/i;` },
  { id: 'G3.lim.deadAlternatives', guard: 'G3 D101', kind: 'LIMIT',
    what: 'restore the two dead alternatives D101 removed (advanced|integrated)',
    from: `const ADJECTIVAL_COMPLETION = /^(closed|completed|restored)$/i;`,
    to:   `const ADJECTIVAL_COMPLETION = /^(closed|completed|restored|advanced|integrated)$/i;` },
  { id: 'G3.lim.broadenAdjectivalReachable', guard: 'G3 D101', kind: 'LIMIT',
    what: 'over-broaden ADJECTIVAL_COMPLETION with REACHABLE completion verbs (deleted|archived|removed|sent)',
    from: `const ADJECTIVAL_COMPLETION = /^(closed|completed|restored)$/i;`,
    to:   `const ADJECTIVAL_COMPLETION = /^(closed|completed|restored|deleted|archived|removed|sent|done|granted|added)$/i;` },
  { id: 'G3.lim.dropPositionRule', guard: 'G3 D86', kind: 'LIMIT',
    what: 'drop run11/D86 position rule (a completion participle after the first word no longer refuses)',
    from: `            if (completionIdx > 0) return null;`,
    to:   `            if (false) return null;` },
  { id: 'G3.lim.dropTitleCase', guard: 'G3 D78', kind: 'LIMIT',
    what: 'drop run10/D78 Title-Case name-shape discriminator',
    from: `            if (!titleCasedName) return null;`,
    to:   `            if (false && !titleCasedName) return null;` },
  { id: 'G3.lim.dropDeterminer', guard: 'G3 D91', kind: 'LIMIT',
    what: 'drop run12/D91 determiner/ALL-CAPS second-word test',
    from: `            if (completionIdx === 0 && words.length > 1\r\n                && (/^[\\p{Lu}0-9]{2,}$/u.test(words[1]) || DETERMINER_OR_PRONOUN.test(words[1]))) return null;`,
    to:   `            if (false) return null;` },

  // ================= G4: D102 raw fallback in matchDisambiguationOption =================
  { id: 'G4.cov.removeFallback', guard: 'G4 D102', kind: 'COVERAGE',
    what: 'remove the raw-label fallback entirely (back to ace9b6a)',
    from: `  if (matches.length > 1) {`,
    to:   `  if (false) {` },
  { id: 'G4.lim.firstNotUnique', guard: 'G4 D102', kind: 'LIMIT',
    what: 'over-broaden: return the FIRST raw match instead of requiring a unique one',
    from: `    if (exact.length === 1) return exact[0];`,
    to:   `    if (exact.length >= 1) return exact[0];` },
  { id: 'G4.lim.noTrimLower', guard: 'G4 D102', kind: 'LIMIT',
    what: 'drop case-folding on the raw comparison',
    from: `      && command.trim().toLowerCase().includes(o.label.trim().toLowerCase()));`,
    to:   `      && command.trim().includes(o.label.trim()));` },

  // ================= G5: D103a collision numbering =================
  { id: 'G5.cov.rawKeyRunningCounter', guard: 'G5 D103a', kind: 'COVERAGE',
    what: 'revert to run12 numbering (raw label key + running counter)',
    from: `            for (let oi = 0; oi < paObj.options.length; oi++) {\r\n              const o = paObj.options[oi];\r\n              if (o && typeof o.label === 'string' && labelCounts.get(labelKey(o.label)) > 1) {\r\n                o.label = \`\${o.label.replace(/\\s*\\(option \\d+\\)$/, '')} (option \${oi + 1})\`;`,
    to:   `            let collisionSeq = 0;\r\n            for (let oi = 0; oi < paObj.options.length; oi++) {\r\n              const o = paObj.options[oi];\r\n              if (o && typeof o.label === 'string' && labelCounts.get(o.label) > 1) {\r\n                collisionSeq++;\r\n                o.label = \`\${o.label} (option \${collisionSeq})\`;` },
  { id: 'G5.cov.constantNumber', guard: 'G5 D103a', kind: 'COVERAGE',
    what: 'number every colliding label (option 1) — numbering that does not disambiguate',
    from: `o.label = \`\${o.label.replace(/\\s*\\(option \\d+\\)$/, '')} (option \${oi + 1})\`;`,
    to:   `o.label = \`\${o.label.replace(/\\s*\\(option \\d+\\)$/, '')} (option 1)\`;` },
  { id: 'G5.lim.collapseAllKeys', guard: 'G5 D103a', kind: 'LIMIT',
    what: 'over-broaden labelKey to collide EVERY label (real distinct names get spuriously numbered)',
    from: `            const labelKey = (s) => s.replace(/[“”‘’"']/g, '').replace(/\\s+/g, ' ').trim().toLowerCase()\r\n              .replace(/\\s*\\(option \\d+\\)$/, '');`,
    to:   `            const labelKey = (s) => '';` },
  { id: 'G5.lim.keyDropsAllPunctuation', guard: 'G5 D103a', kind: 'LIMIT',
    what: 'over-broaden labelKey to ignore all non-alphanumerics (distinct real names collide)',
    from: `.replace(/\\s*\\(option \\d+\\)$/, '');`,
    to:   `.replace(/\\s*\\(option \\d+\\)$/, '').replace(/[^a-z0-9]/g, '');` },

  // ================= G6: readsAsCompletion + the two new belts =================
  { id: 'G6.cov.dropConfirmedCompletion', guard: 'G6 D103c', kind: 'COVERAGE',
    what: 'drop CONFIRMED_COMPLETION from readsAsCompletion',
    from: `          || EXECUTION_IN_PROGRESS.test(s) || CONFIRMED_COMPLETION.test(s)\r\n          || REFERENCELESS_CONFIRMATION.test(s);`,
    to:   `          || EXECUTION_IN_PROGRESS.test(s)\r\n          || REFERENCELESS_CONFIRMATION.test(s);` },
  { id: 'G6.cov.dropReferenceless', guard: 'G6 D103c', kind: 'COVERAGE',
    what: 'drop REFERENCELESS_CONFIRMATION from readsAsCompletion',
    from: `          || EXECUTION_IN_PROGRESS.test(s) || CONFIRMED_COMPLETION.test(s)\r\n          || REFERENCELESS_CONFIRMATION.test(s);`,
    to:   `          || EXECUTION_IN_PROGRESS.test(s) || CONFIRMED_COMPLETION.test(s);` },
  { id: 'G6.lim.referencelessNoEndAnchor', guard: 'G6 D103c', kind: 'LIMIT',
    what: 'remove REFERENCELESS_CONFIRMATION\'s end anchor (swallows substantive confirmations)',
    from: `(\\s*\\(option\\s+\\d+\\))?\\s*[.!]?\\s*$/i;`,
    to:   `(\\s*\\(option\\s+\\d+\\))?\\s*[.!]?\\s*/i;` },
  { id: 'G6.lim.confirmedNoStartAnchor', guard: 'G6 D103c', kind: 'LIMIT',
    what: 'remove CONFIRMED_COMPLETION\'s ^ start anchor',
    from: `const CONFIRMED_COMPLETION = /^\\s*confirmed`,
    to:   `const CONFIRMED_COMPLETION = /\\s*confirmed` },
  { id: 'G6.lim.referencelessNoStartAnchor', guard: 'G6 D103c', kind: 'LIMIT',
    what: 'remove REFERENCELESS_CONFIRMATION\'s ^ start anchor',
    from: `const REFERENCELESS_CONFIRMATION = /^\\s*confirmed`,
    to:   `const REFERENCELESS_CONFIRMATION = /\\s*confirmed` },
  { id: 'G6.arm.legacyPrivateCopy', guard: 'G6 both-arms', kind: 'COVERAGE',
    what: 'legacyProseFallback reverts to its OWN private pattern copy (arm 1 left behind)',
    from: `          && readsAsCompletion(String(result.summary || ''));\r\n\r\n        // run7/D52`,
    to:   `          && (LEGACY_PAST_COMPLETION.test(String(result.summary || '')) || EXECUTION_IN_PROGRESS.test(String(result.summary || '')));\r\n\r\n        // run7/D52` },
  { id: 'G6.arm.unaccountedPrivateCopy', guard: 'G6 both-arms', kind: 'COVERAGE',
    what: 'unaccountedCompletionProse reverts to its OWN private pattern copy (arm 2 left behind)',
    from: `        const unaccountedCompletionProse = !hasSupportedMutationClaim\r\n          && readsAsCompletion(String(result.summary || ''));`,
    to:   `        const unaccountedCompletionProse = !hasSupportedMutationClaim\r\n          && (LEGACY_PAST_COMPLETION.test(String(result.summary || '')) || EXECUTION_IN_PROGRESS.test(String(result.summary || '')));` },

  // ================= G7: the disambiguation REPLAY site =================
  { id: 'G7.cov.revertReplaySummary', guard: 'G7 replay', kind: 'COVERAGE',
    what: 'revert the replay summary to the pre-fix "Confirmed — <label>."',
    from: `              summary: (isTypedFallbackOnly || readsAsAssertion)\r\n                ? 'Confirmed — proceeding with the option you selected.'\r\n                : \`Confirmed — you selected “\${replayLabel}”.\`,`,
    to:   `              summary: \`Confirmed — \${matchedOption.label}.\`,` },
  { id: 'G7.lim.dropTypedFallbackTest', guard: 'G7 replay', kind: 'LIMIT',
    what: 'drop the isTypedFallbackOnly degradation (a numbered typed fallback replays as a named choice)',
    from: `              summary: (isTypedFallbackOnly || readsAsAssertion)`,
    to:   `              summary: (false || readsAsAssertion)` },
  { id: 'G7.lim.dropAssertionTest', guard: 'G7 replay', kind: 'LIMIT',
    what: 'drop the readsAsAssertion degradation',
    from: `              summary: (isTypedFallbackOnly || readsAsAssertion)`,
    to:   `              summary: (isTypedFallbackOnly || false)` },
  { id: 'G7.lim.alwaysNeutral', guard: 'G7 replay', kind: 'LIMIT',
    what: 'over-broaden: every replay degrades to the neutral acknowledgement (the founder never sees which option)',
    from: `              summary: (isTypedFallbackOnly || readsAsAssertion)`,
    to:   `              summary: (true || readsAsAssertion)` },
];
