// Roll qa/verification/CURRENT_CAMPAIGN.json for verifier #56 (campaign #116): record the P1
// package, the founder's bar change, the reversal of the #50 decision, and the pre-dispatch state.
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
const p = 'qa/verification/CURRENT_CAMPAIGN.json';
const j = JSON.parse(readFileSync(p, 'utf8'));
const sha = execSync('git rev-parse HEAD').toString().trim();
const idx = execSync('sha256sum supabase/functions/sem-ai-command/index.ts').toString().split(' ')[0];
j.previous_campaign_pointer = { campaign: j.campaign, verifier: j.verifier, index_sha256_prefix: j.index_sha256_prefix };
j.campaign = 119; j.verifier = 59; j.kind = 'CONTRACT-CONFORMANCE DEPLOY GATE (v92 = reference corpus, never the bar)';
j.status = 'DISPATCH PENDING — verifier #59 on the #58 closure';
j.closure_commit = sha; j.index_sha256_prefix = idx.slice(0, 16);
j.branch = 'p1/execution-truth-governance';
j.deploy_rule = 'FOUNDER RULING 2026-09-07: PRODUCT CONTRACT OUTRANKS V92 PARITY. The deploy bar is conformance to governance/OPERATING_TRUTH_MODEL.md (final-claim rule, request intent, never-silent receipt, envelopes, precedence, persistence). Deployed v92 is a reference corpus for truth-regression measurement; a class that matches v92 but violates the contract is a defect; an intended departure from v92 that satisfies the contract is not a failure.';
j.open_not_blocking = (j.open_not_blocking || []).map((s) => s.startsWith('DECISION (founder may overrule): belt skips pendingAction turns')
  ? 'SUPERSEDED by the founder ruling 2026-09-07: the belt no longer skips pendingAction turns; both belt consumers gate on REQUEST intent (requestedIntent !== null) and never on pendingAction; a mutation-intent turn with no verified execution ends in the deterministic receipt. v49-v53 pendingAction-term pins are marked SUPERSEDED in place.'
  : s);
j.verifier58_closure = 'Ledger #131: #58 prepared fix F1/F2/F3 applied as written — imperative-position allow-list for the command fallback; archivedTasks placed in the pack; task and goal lifecycle ids re-read server-side across every status with truthful unresolved lines; entity-aware receipt. #58 suite promoted (48/0); #57 306/0; #56 129/0; matrix 31/31; collection envelope 57/57.';
j.verifier57_closure = 'Ledger #129: #57 prepared fix F1/F2/F3 applied as written (other vetoes the lexicon; fallback honours requestIntent.entityType; non-imperative leads refused) plus D4 whole-name candidate query, D6a polite lifecycle question, D6b honest receipt reason. #57 suite promoted (306/0); matrix 31/31; mutation proof 5/5; generators FN 0.5% FP 0; battery 55/55.';
j.verifier56_closure = 'Ledger #127: structured requestIntent (schema + prompt) validated server-side; request lexicon (Unicode lookarounds, passive shapes, object guards, case-sensitive proper nouns, tail shape, read-shape veto, polite-question exemption); the belt never decides intent; command fallback imperative-only, direction by first verb, exact executes / fuzzy asks, full-remainder + comma-head candidates, model requestIntent.targetName as a name source; receipt keeps questions; history verified=null when nothing executed and no intent; stored pendingAction expires in 30 min. #56 suite promoted to the battery; generators in-tree; mutation proof 8/8.';
j.what_this_campaign_did = 'P1 package for the Work-PC handover 2026-09-07 (BUG-010/014/002/012/013/011) implemented as the first feature under docs/architecture/FEATURE_COMPLETENESS_CONTRACT.md: ExecutionResultEnvelope on every recordExecution site with fresh create-family postconditions; MutationIntent from the request (verb patterns, model action arrays, confirmation-shaped commands); never-silent receipt; server-side company lifecycle resolution across every status (restoreCompanyNames/archiveCompanyNames schema fields; contextCompanyIds no longer gates archive/restore); context.collections envelopes for every pack collection, companies split active/archived; narrative tier with verdict + UNVERIFIED marker; durable channel state first; work_orders.output persisted every turn with turnVerdict; person-assignment receipt from the executed diff; V55-D1 possessive fix carried. Web: callLifecycleRpc, archived-parent policy on People controls, manager picker semantics, Archived (N) affordance, COMPANY_REF in 22 files, scopeToActiveOrganization in 19 pages. Enforcement: 8 architecture_* contracts + company_lifecycle_matrix + grounding_precedence_canonical_over_history + mutation_receipt_equals_ledger + tenant_authorization_lifecycle.sql.';
j.implementing_session_evidence_not_to_be_trusted = 'battery 53/53; gates v48-v55 green, v46 33/3 (recorded standing reds: C8a stale CRLF pin, D1 growth exponent, D5 withdrawn); deno 19 by class (TS7006 x10, TS2322 x6, TS7034, TS7005, TS2339; zero runtime-fatal); index.ts CRLF 0 bare LF; web tsc/eslint/next build clean. RE-DERIVE ALL OF IT.';
j.verifier59_base_commit = sha;
j.verifier59_index_sha256 = idx;
j.verifier59_started_at = null;
j.verifier59_status = 'not started';
j.verifier59_findings = [];
j.verdict = null;
j.open_deploy_blockers = ['verifier #59 has not run'];
j.harness_changes_to_judge = ['_gate_extract.mjs REQUEST_SIDE_DEFAULTS above every window (command "" by default = no intent)', 'run8/10/11/12/13/14 per-call command (default mutation intent; read cases pass "")', 'run8 D59 re-reversed; run11 V11.durable.livePrecedence inverted (durable first) + V11.durable.fallback added', 'lifecycle_evidence section S literals (company sites carry envelope detail; create family via recordCreate) and P6 inverted (persist every turn)', 'v49-v53 request-side globals + SUPERSEDED pendingAction-term pins; scratch/v53/harness.mjs self-check inverted', 'v92_open_regression_contract decision window takes requestedIntent', 'company_ref_no_bare_name_join counts ${COMPANY_REF}; org_selector_scoping_coverage accepts scopeToActiveOrganization'];
j.rules = 'FOUNDER RULING 2026-09-07 replaces the v92-differential certification rule (previous rule text retained in git history): a verifier PASS on the EXACT new SHA under the CONTRACT BAR (conformance to governance/OPERATING_TRUTH_MODEL.md; v92 parity is not deployability) is production-deployment certification. Ask ALLOW_FUNCTIONS_DEPLOY=1 exactly once, only after such a PASS on these exact bytes. Production stays v92 until then. qa/BUG_QUEUE.json, qa/COVERAGE_LEDGER.json, qa/FIXTURE_REGISTRY.json, qa/HANDOFF_STATE.json are Work-PC single-writer files: read-only.';
writeFileSync(p, JSON.stringify(j, null, 2) + '\n');
console.log('campaign rolled to #119 / verifier #59 at', sha.slice(0, 7), idx.slice(0, 16));
