#!/usr/bin/env node
// CANDIDATE INVENTORY (WO-10 "the candidate report lists every table, function, route, secret name and environment variable"). Read
// from the source at the checked-out commit - never typed by hand - and printed as Markdown for the candidate report.
//   node qa/implementation/auto-enrollment-v1/tools/candidate_inventory.mjs > inventory.md
import { readdirSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const read = (p) => readFileSync(join(ROOT, p), 'utf8').replace(/\r\n/g, '\n');
const files = (dir, re) => { const out = []; const walk = (d) => { for (const e of readdirSync(join(ROOT, d), { withFileTypes: true })) { const p = d + '/' + e.name; if (e.isDirectory()) walk(p); else if (re.test(e.name)) out.push(p); } }; walk(dir); return out.sort(); };
const uniq = (a) => [...new Set(a)].sort();
const tick = (s) => '`' + s + '`';
const head = execFileSync('git', ['-C', ROOT, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
const out = [];
const say = (s = '') => out.push(s);

say('# Candidate inventory');
say();
say('Generated by ' + tick('qa/implementation/auto-enrollment-v1/tools/candidate_inventory.mjs') + ' at ' + tick(head) + '.');
say();

// ---- SQL
const sqlFiles = files('supabase/control-plane/v1', /\.sql$/);
const sql = sqlFiles.map((f) => ({ f, t: read(f) }));
const created = [], altered = [], funcs = [], roles = [], triggers = [];
for (const { f, t } of sql) {
  const part = f.split('/').pop();
  for (const m of t.matchAll(/^create table (factory\.[a-z0-9_]+)/gm)) created.push({ name: m[1], part });
  for (const m of t.matchAll(/^alter table (factory\.[a-z0-9_]+)\s+add column/gm)) altered.push(m[1]);
  for (const m of t.matchAll(/create (?:or replace )?function (factory\.[a-z0-9_]+)\(([^)]*)\)\s*returns ([a-z0-9_.]+)/g)) {
    funcs.push({ name: m[1], args: m[2].replace(/\s+/g, ' ').trim(), ret: m[3], definer: /security definer/.test(t.slice(m.index, m.index + 600)), part });
  }
  for (const m of t.matchAll(/create role ([a-z0-9_]+)/g)) roles.push(m[1]);
  for (const m of t.matchAll(/^create trigger ([a-z0-9_]+)\s+(?:before|after)[^;]*? on (factory\.[a-z0-9_]+)/gms)) triggers.push(m[1] + ' on ' + m[2]);
  for (const m of t.matchAll(/execute format\('create trigger ([a-z0-9_]+) [^']*? on factory\.%I/g)) triggers.push(m[1] + ' on each table of the ' + part + ' loop');
}
say('## Migration');
say();
say(tick('supabase/control-plane/v1/') + ' composed into one transaction by ' + tick('scripts/factory-control-plane/migration.mjs') + ' (' + sqlFiles.length + ' parts):');
say();
for (const f of sqlFiles) say('- ' + tick(f.split('/').pop()));
say();
say('### Tables created (' + created.length + ')');
say();
for (const c of created) say('- ' + tick(c.name) + ' (' + c.part + ')');
say();
say('### Existing (69df2f52) tables that gain columns (' + uniq(altered).length + ')');
say();
for (const a of uniq(altered)) say('- ' + tick(a));
say();
say('### Roles created (' + uniq(roles).length + ', all NOLOGIN)');
say();
for (const r of uniq(roles)) say('- ' + tick(r));
say();
say('### Triggers (' + uniq(triggers).length + ')');
say();
for (const t of uniq(triggers)) say('- ' + tick(t.split(' ')[0]) + ' ' + t.split(' ').slice(1).join(' '));
say();
const doors = funcs.filter((x) => /^factory\.(node|admin)_/.test(x.name));
const internal = funcs.filter((x) => !/^factory\.(node|admin)_/.test(x.name));
say('### Front doors: the SECURITY DEFINER functions the APIs execute (' + doors.length + ')');
say();
say('| function | returns | definer | part |');
say('|---|---|---|---|');
for (const d of doors) say('| ' + tick(d.name + '(' + d.args + ')') + ' | ' + d.ret + ' | ' + (d.definer ? 'yes' : 'no') + ' | ' + d.part + ' |');
say();
say('### Internal functions (' + internal.length + '; no API role executes them)');
say();
say(internal.map((x) => tick(x.name)).join(', '));
say();

// ---- routes
const EDGE = 'supabase/control-plane/edge/supabase/functions';
const nodeApi = read(EDGE + '/_shared/node_api.ts');
const adminApi = read(EDGE + '/_shared/admin_api.ts');
const routes = [...((/export const FRONT_DOORS[^=]*=\s*\{([\s\S]*?)\n\};/.exec(nodeApi) || ['', ''])[1]).matchAll(/'((?:GET|POST) \/v1\/[a-z/-]+)':\s*'select factory\.([a-z0-9_]+)\(/g)];
const ops = [...((/export const ADMIN_OPS[^=]*=\s*\{([\s\S]*?)\n\};/.exec(adminApi) || ['', ''])[1]).matchAll(/'([a-z-]+)':\s*\{\s*fn:\s*'([a-z0-9_]+)',\s*code:\s*(true|false)/g)];
say('## Routes');
say();
say('Base URLs, deployed by the founder on project ' + tick('npvhuoozkbexddnvkqsj') + ': ' + tick('https://npvhuoozkbexddnvkqsj.supabase.co/functions/v1/factory-node-api')
  + ' and ' + tick('.../factory-admin-api') + '. The platform delivers each function its paths under ' + tick('/<function name>') + ' (route.ts).');
say();
say('### Factory Node API (S-7; ' + routes.length + ' routes)');
say();
say('| route | front door |');
say('|---|---|');
for (const m of routes) say('| ' + tick(m[1]) + ' | ' + tick('factory.' + m[2]) + ' |');
say();
say('### Factory Admin API (' + ops.length + ' operations, each ' + tick('POST /v1/admin/<op>') + ' with the caller\'s own Brain OS token)');
say();
say('| op | front door | issues a pairing code |');
say('|---|---|---|');
for (const m of ops) say('| ' + tick(m[1]) + ' | ' + tick('factory.' + m[2]) + ' | ' + (m[3] === 'true' ? 'yes (shown once)' : 'no') + ' |');
say();
const webRoutes = files('web/app/(app)/software-factory', /^page\.tsx$/).map((f) => f.replace(/^web\/app\/\(app\)/, '').replace(/\/page\.tsx$/, ''));
say('### Brain OS web routes');
say();
for (const r of webRoutes.filter((r) => /computers|workers/.test(r))) say('- ' + tick(r) + (/workers/.test(r) ? ' (retired: redirects to /software-factory/computers)' : ''));
say();

// ---- secrets and environment
const edgeEntry = [EDGE + '/factory-node-api/index.ts', EDGE + '/factory-admin-api/index.ts'];
const secretUse = {};
for (const f of edgeEntry) for (const m of read(f).matchAll(/Deno\.env\.get\('([A-Z0-9_]+)'\)/g)) (secretUse[m[1]] ||= new Set()).add(f.split('/')[5]);
say('## Edge secret and configuration names (the Factory project\'s function secret store; values are set by the founder and appear nowhere in the repository)');
say();
say('| name | read by |');
say('|---|---|');
for (const k of Object.keys(secretUse).sort()) say('| ' + tick(k) + ' | ' + [...secretUse[k]].sort().join(', ') + ' |');
say();
const envFiles = [...files('scripts/factory-runner/enrolled', /\.mjs$/), 'scripts/factory-runner/sea/main.mjs', ...files('scripts/factory-build', /\.mjs$/),
  ...files('scripts/factory-control-plane', /\.mjs$/), ...files('web/lib/factory', /\.ts$/), 'web/lib/data/factory-computers.ts'];
const envs = {};
for (const f of envFiles) for (const m of read(f).matchAll(/process\.env\.([A-Za-z_][A-Za-z0-9_]*)|process\.env\[['"]([A-Za-z_][A-Za-z0-9_]*)['"]\]/g)) (envs[m[1] || m[2]] ||= new Set()).add(f);
say('## Environment variables read by the candidate\'s runtime, build, migration and web code');
say();
say('| variable | read by |');
say('|---|---|');
for (const k of Object.keys(envs).sort()) say('| ' + tick(k) + ' | ' + [...envs[k]].map(tick).join(', ') + ' |');
say();
say('No variable above holds a secret the repository supplies. ' + tick('FACTORY_ADMIN_API_URL') + ' / ' + tick('FACTORY_RELEASES_URL') + ' (web) are non-secret and accept only a Supabase project over HTTPS or a loopback harness.');
process.stdout.write(out.join('\n') + '\n');
