// Generates the launch configs handed to every QA Director invocation, plus the machine-local
// seat marker.
//
// They are REGENERATED on every supervisor boot rather than hand-maintained, because both embed
// absolute Windows paths. A stale hardcoded path here would not fail loudly - it would produce a
// director with no browser, or with no safety hook, which is far worse than a crash. Regenerating
// makes the paths a function of where the code actually lives.
//
// Founder decisions 2026-09-10 applied here:
//   - The Director's browser is ISOLATED (in-memory --isolated profile; sidecar output files under
//     qa/runner/.director-profile), on the version-pinned @playwright/mcp, with origins confined to
//     the product. It never opens the founder's default Chrome profile. Without a bootstrapped `qa-director` synthetic identity it
//     starts logged out and must record UI work BLOCKED: IDENTITY_NOT_PROVISIONED.
//   - The deny list and hook are DEFENSE IN DEPTH. The barrier is capability absence: the Work PC
//     holds no production control-plane credential (A4) and workers have no shell (worker-policy).
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { P, RUNNER_DIR } from './paths.mjs';
import { join } from 'node:path';
import { PLAYWRIGHT_MCP_VERSION, BROWSER_QA_DENY } from './worker-policy.mjs';
import { DEFAULT_ALLOWED_ORIGINS } from './browser-isolation.mjs';

const HOOK = join(RUNNER_DIR, 'hooks', 'block-destructive.mjs');
export const DIRECTOR_PROFILE_DIR = join(RUNNER_DIR, '.director-profile');
export const DIRECTOR_IDENTITY_PATH = join(RUNNER_DIR, '.auth', 'qa-director.json');
export const SEAT_MARKER_PATH = join(RUNNER_DIR, '.seat');

function writeIfChanged(path, obj) {
  const next = JSON.stringify(obj, null, 2) + '\n';
  if (existsSync(path)) {
    try { if (readFileSync(path, 'utf8') === next) return false; } catch {}
  }
  writeFileSync(path, next);
  return true;
}

/** Machine-local, gitignored. Read by run-sql-regressions.mjs so the refusal does not depend on env. */
export function ensureSeatMarker() {
  if (!existsSync(SEAT_MARKER_PATH)) writeFileSync(SEAT_MARKER_PATH, 'WORK_PC\n');
  return SEAT_MARKER_PATH;
}

export function ensureLaunchConfigs() {
  mkdirSync(DIRECTOR_PROFILE_DIR, { recursive: true });
  ensureSeatMarker();
  const directorIdentity = existsSync(DIRECTOR_IDENTITY_PATH);

  // --isolated = in-memory profile (0.0.80 refuses --user-data-dir alongside it). Nothing from a
  // director session persists on disk; DIRECTOR_PROFILE_DIR is kept only for sidecar output files.
  const args = [
    '@playwright/mcp@' + PLAYWRIGHT_MCP_VERSION,
    '--isolated',
    '--output-dir', DIRECTOR_PROFILE_DIR,
    '--allowed-origins', DEFAULT_ALLOWED_ORIGINS.join(';'),
  ];
  if (directorIdentity) args.push('--storage-state', DIRECTOR_IDENTITY_PATH);

  const mcp = {
    _doc: 'Passed to every director via --mcp-config. Declared EXPLICITLY rather than inherited, and '
      + 'ISOLATED: in-memory --isolated profile (output files under qa/runner/.director-profile), pinned @playwright/mcp version, origins '
      + 'confined to the product. The founder browser profile is never opened by an unattended director. '
      + 'Regenerated by qa/runner/lib/config.mjs.',
    _identity: directorIdentity ? 'qa-director (synthetic, bootstrapped by founder/Home PC)' : 'NONE - UI work is BLOCKED: IDENTITY_NOT_PROVISIONED',
    _mcp_version: PLAYWRIGHT_MCP_VERSION,
    mcpServers: {
      playwright: { type: 'stdio', command: 'npx', args, env: {} },
    },
  };

  const settings = {
    _doc: 'Safety settings for the UNATTENDED QA Director. DEFENSE IN DEPTH ONLY: the deny list and the '
      + 'PreToolUse hook catch mistakes; the actual barrier is that this machine holds no production '
      + 'control-plane credential and that worker classes have no shell (qa/runner/lib/worker-policy.mjs). '
      + 'See CLAUDE.md #22 for the incident that motivated the hook.',
    permissions: {
      deny: [
        'Bash(supabase db:*)',
        'Bash(supabase migration:*)',
        'Bash(supabase sql:*)',
        'Bash(supabase functions deploy:*)',
        'Bash(supabase login:*)',
        'Bash(supabase link:*)',
        'Bash(psql:*)',
        'Bash(pgcli:*)',
        'Bash(pg_dump:*)',
        'Bash(vercel deploy:*)',
        'Bash(vercel promote:*)',
        'Bash(vercel rollback:*)',
        'Bash(vercel login:*)',
        'Bash(vercel link:*)',
        'Bash(node qa/runner/run-sql-regressions.mjs:*)',
        'WebFetch(domain:pvphxgrtdfrudejjhzjk.supabase.co)',
        ...BROWSER_QA_DENY,
      ],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash|PowerShell|WebFetch|mcp__.*',
          hooks: [{ type: 'command', command: 'node "' + HOOK + '"', timeout: 15 }],
        },
      ],
    },
  };

  return {
    mcpChanged: writeIfChanged(P.mcpConfig, mcp),
    settingsChanged: writeIfChanged(P.guardSettings, settings),
    hookPath: HOOK,
    hookExists: existsSync(HOOK),
    directorIdentity,
    directorProfileDir: DIRECTOR_PROFILE_DIR,
  };
}
