// Generates the two launch configs handed to every QA Director invocation.
//
// They are REGENERATED on every supervisor boot rather than hand-maintained, because both embed
// absolute Windows paths. A stale hardcoded path here would not fail loudly - it would produce a
// director with no browser, or with no safety hook, which is far worse than a crash. Regenerating
// makes the paths a function of where the code actually lives.
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { P, RUNNER_DIR } from './paths.mjs';
import { join } from 'node:path';

const HOOK = join(RUNNER_DIR, 'hooks', 'block-destructive.mjs');

function writeIfChanged(path, obj) {
  const next = JSON.stringify(obj, null, 2) + '\n';
  if (existsSync(path)) {
    try { if (readFileSync(path, 'utf8') === next) return false; } catch {}
  }
  writeFileSync(path, next);
  return true;
}

export function ensureLaunchConfigs() {
  const mcp = {
    _doc: 'Passed to every director via --mcp-config. Declared EXPLICITLY rather than inherited: '
      + 'the Playwright server is registered in the user config against the parent directory, not '
      + 'the repo, so an unattended director could otherwise start with no browser and still report '
      + 'UI results. Regenerated by qa/runner/lib/config.mjs.',
    mcpServers: {
      playwright: { type: 'stdio', command: 'npx', args: ['@playwright/mcp@latest'], env: {} },
    },
  };

  const settings = {
    _doc: 'Safety settings for the UNATTENDED QA Director. The deny list is defence in depth; the '
      + 'PreToolUse hook is the actual barrier because it inspects the real command string rather '
      + 'than matching a prefix. See CLAUDE.md #22 for the incident that motivated it.',
    permissions: {
      deny: [
        'Bash(supabase db push:*)',
        'Bash(supabase db reset:*)',
        'Bash(supabase migration up:*)',
        'Bash(supabase migration repair:*)',
        'Bash(supabase functions deploy:*)',
        'Bash(vercel deploy:*)',
        'Bash(vercel promote:*)',
        'Bash(vercel rollback:*)',
      ],
    },
    hooks: {
      PreToolUse: [
        {
          matcher: 'Bash|PowerShell',
          hooks: [{ type: 'command', command: 'node "' + HOOK + '"', timeout: 15 }],
        },
      ],
    },
  };

  return {
    mcpChanged: writeIfChanged(P.mcpConfig, mcp),
    settingsChanged: writeIfChanged(P.guardSettings, settings),
    hookPath: HOOK,
    hookExists: existsSync(HOOK),
  };
}
