#!/usr/bin/env node
// ARTIFACT RELAY V0 - THE INSTALLER. One bounded operation on the dedicated NON-PRODUCTION Factory control plane, run by the
// founder with the founder's own access token. It never asks for, reads or prints the project's service key.
//
//   node relay/install.mjs --plan          print exactly what it would change; needs no token and touches nothing
//   node relay/install.mjs                 install (or finish an install that was cut off): safe to run again
//   node relay/install.mjs --uninstall     remove what it installed
//
// What it does, in order, stopping at the first thing that is not as it must be:
//    1 this checkout: a clean tree at a commit signed by the implementer key, every file equal to MANIFEST.sha256
//    2 the verifier's registration: the Director-signed commit on top of this exact commit (branch factory/artifact-relay-v0-verifier)
//    3 the Director's record of the founder-approved change (AC-10 / S-11), so that the install is never read as a finding
//    4 pre-check (read-only)                 7 register the two nodes: this node as sender, the Director's node as verifier
//    5 the schema, in one transaction        8 post-check (read-only)
//    6 the private bucket                    9 deploy the function, JWT verification off, with the same two registrations
//                                           10 selfcheck from this node, through the deployed function
// and prints one PASS or FAIL, with a receipt that holds no secret.
//
// The token is read from SUPABASE_ACCESS_TOKEN (relay/install.ps1 asks for it without echo). It needs to run SQL and deploy a
// function on the Factory project and nothing else; a fine-grained, short-lived token limited to that project is enough.
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RelayError, call, loadConfig, publicKey, relayHome } from './lib/client.mjs';
import { commitSigner } from './lib/gitsig.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FUNCTION = 'factory-artifact-relay';
const BUCKET = 'factory-private-artifacts';
const FUNCTION_DIR = 'supabase/functions/' + FUNCTION;

/** the one project this installer changes, and the identities it trusts. There is no option that names another project. */
const REAL = Object.freeze({
  project: 'npvhuoozkbexddnvkqsj',
  api: 'https://api.supabase.com',
  relayUrl: 'https://npvhuoozkbexddnvkqsj.supabase.co/functions/v1/' + FUNCTION,
  remote: 'origin',
  implementerFingerprint: 'SHA256:9zUYxsZkV6MLq9dcGtiz+e3D/h0XPevf3w/cJH5QTek',
  directorFingerprint: 'SHA256:JuFaA95213JN0+3f/RAlUOAOK7G42IukX/qQiWeIALE',
  directorBranch: 'factory/auto-enrollment-v1-director',
  directorLedger: 'qa/work-orders/AUTO_ENROLLMENT_V1_LEDGER.json',
  verifierBranch: 'factory/artifact-relay-v0-verifier',
  cli: null,
  root: ROOT,
});

class Stop extends Error { constructor(message, code = 1) { super(message); this.code = code; } }
const say = (line = '') => process.stdout.write(line + '\n');
const sha256 = (b) => createHash('sha256').update(b).digest('hex');
const NODE_ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{2,99}$/, KEY = /^[A-Za-z0-9_-]{43}$/;

/** the tests point the installer at a loopback stand-in and a project that is named as a test; nothing else is accepted */
function settings() {
  const file = process.env.RELAY_INSTALL_TEST_SETTINGS;
  if (!file) return REAL;
  const t = JSON.parse(readFileSync(file, 'utf8'));
  const api = new URL(t.api), relay = new URL(t.relayUrl);
  if (api.protocol !== 'http:' || api.hostname !== '127.0.0.1' || relay.hostname !== '127.0.0.1' || !/^test-[a-z0-9]{6,20}$/.test(t.project)) {
    throw new Stop('test settings must name a loopback stand-in and a project whose name starts with test-', 2);
  }
  return Object.freeze({ ...REAL, ...t, test: true });
}

/** registry.ts for a deployment: the same bytes for the same registrations, on every machine */
export function renderRegistry(nodes) {
  for (const n of nodes) {
    if (!NODE_ID.test(n.node_id) || !KEY.test(n.public_key) || (n.relay_role !== 'sender' && n.relay_role !== 'verifier')) throw new Stop('a registration is not well formed', 2);
  }
  if (new Set(nodes.map((n) => n.node_id)).size !== nodes.length || new Set(nodes.map((n) => n.relay_role)).size !== nodes.length) throw new Stop('the registrations are not one sender and one verifier', 2);
  return [
    '// THE NODES THIS FUNCTION AUTHENTICATES. GENERATED by relay/install.mjs from the founder\'s registration: do not edit.',
    'export type RegisteredNode = { node_id: string; relay_role: "sender" | "verifier"; public_key: string };',
    '',
    'export const REGISTRY: RegisteredNode[] = [',
    ...nodes.map((n) => `  { node_id: ${JSON.stringify(n.node_id)}, relay_role: ${JSON.stringify(n.relay_role)}, public_key: ${JSON.stringify(n.public_key)} },`),
    '];',
    '',
  ].join('\n');
}

/** a verifier's registration file: exactly these four fields */
export function parseRegistration(text) {
  let j;
  try { j = JSON.parse(text); } catch { throw new Stop('the verifier registration is not JSON', 3); }
  if (j === null || typeof j !== 'object' || Array.isArray(j) || Object.keys(j).sort().join() !== 'node_id,public_key,relay,relay_role' || j.relay !== 'artifact-relay/v0'
      || j.relay_role !== 'verifier' || typeof j.node_id !== 'string' || !NODE_ID.test(j.node_id) || typeof j.public_key !== 'string' || !KEY.test(j.public_key)) {
    throw new Stop('the verifier registration is not exactly { relay, node_id, relay_role: "verifier", public_key }', 3);
  }
  return { node_id: j.node_id, relay_role: 'verifier', public_key: j.public_key };
}

async function main(argv) {
  const flags = new Set(argv.filter((a) => a.startsWith('--') && !a.includes('=')));
  const valueOf = (name) => { const i = argv.indexOf(name); return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : null; };
  for (const f of flags) if (!['--plan', '--uninstall', '--without-director-record', '--verifier-registration', '--leave-bucket'].includes(f)) throw new Stop('unknown option ' + f, 2);
  const PLAN = flags.has('--plan'), UNINSTALL = flags.has('--uninstall');
  const S = settings();
  const git = (...a) => execFileSync('git', ['-C', S.root, ...a], { encoding: 'utf8', maxBuffer: 1 << 26, stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  const gitRaw = (...a) => execFileSync('git', ['-C', S.root, ...a], { maxBuffer: 1 << 26, stdio: ['ignore', 'pipe', 'pipe'] });
  const steps = [];
  const step = (name, outcome, detail = '') => { steps.push({ step: name, outcome, detail, at: new Date().toISOString() }); say(`${String(steps.length).padStart(2)}  ${name.padEnd(46, '.')} ${outcome}${detail ? '  ' + detail : ''}`); };
  const token = process.env.SUPABASE_ACCESS_TOKEN ?? '';
  const clean = (text) => (token ? String(text).split(token).join('<token>') : String(text));

  say(`ARTIFACT RELAY V0 - ${UNINSTALL ? 'removal from' : PLAN ? 'plan for' : 'install on'} project ${S.project}${S.test ? ' (A TEST STAND-IN)' : ' (the dedicated NON-PRODUCTION Factory control plane)'}`);

  // ---------------------------------------------------------------------------------------------------------- 1 this checkout
  if (Number(process.versions.node.split('.')[0]) < 18) throw new Stop('Node 18 or later is required', 2);
  if (git('status', '--porcelain') !== '') throw new Stop('this checkout has changes that are not committed: the installer applies committed bytes only', 2);
  const head = git('rev-parse', 'HEAD');
  const signer = commitSigner(gitRaw('cat-file', 'commit', head));
  if (!signer.ok || signer.fingerprint !== S.implementerFingerprint) throw new Stop('the commit ' + head + ' is not signed by the implementer key ' + S.implementerFingerprint, 2);
  const manifest = readFileSync(join(S.root, 'MANIFEST.sha256'), 'utf8').replace(/\r\n/g, '\n').trim().split('\n').map((l) => ({ sha256: l.slice(0, 64), file: l.slice(66) }));
  for (const m of manifest) {
    if (!existsSync(join(S.root, m.file)) || sha256(readFileSync(join(S.root, m.file))) !== m.sha256 || sha256(gitRaw('show', head + ':' + m.file)) !== m.sha256) {
      throw new Stop(m.file + ' is not the committed file MANIFEST.sha256 lists', 2);
    }
  }
  const file = (rel) => { if (!manifest.some((m) => m.file === rel)) throw new Stop(rel + ' is not in MANIFEST.sha256', 2); return readFileSync(join(S.root, rel), 'utf8'); };
  let cfg;
  try { cfg = loadConfig(); } catch (e) { if (!(e instanceof RelayError)) throw e; throw new Stop(e.message, 2); }
  if (cfg.relay_role !== 'sender') throw new Stop('this node\'s relay identity is ' + cfg.relay_role + ': the installer runs on the sender', 2);
  if (cfg.url !== S.relayUrl) throw new Stop('this node\'s relay identity points at ' + cfg.url + ', not at ' + S.relayUrl, 2);
  const sender = { node_id: cfg.node_id, relay_role: 'sender', public_key: publicKey() };
  step('this checkout', 'OK', `commit ${head} signed by the implementer key; ${manifest.length} files equal MANIFEST.sha256`);

  if (UNINSTALL) return await uninstall();

  // -------------------------------------------------------------------------------------------- 2 the verifier's registration
  let verifier = null, verifierSource = null;
  const given = valueOf('--verifier-registration');
  if (given) {
    verifier = parseRegistration(readFileSync(given, 'utf8'));
    verifierSource = 'a file the founder supplied (not Director-signed)';
  } else {
    let tip = null;
    try {
      if (!PLAN) git('fetch', '--quiet', S.remote, '+refs/heads/' + S.verifierBranch + ':refs/relay-install/verifier');
      tip = git('rev-parse', '--verify', '--quiet', 'refs/relay-install/verifier');
    } catch { tip = null; }
    if (tip) {
      const v = commitSigner(gitRaw('cat-file', 'commit', tip));
      if (!v.ok || v.fingerprint !== S.directorFingerprint) throw new Stop('the verifier registration commit ' + tip + ' is not signed by the Director key ' + S.directorFingerprint, 3);
      if (v.parents.length !== 1 || v.parents[0] !== head) throw new Stop('the verifier registration commit ' + tip + ' is not made on top of this relay commit ' + head, 3);
      if (git('diff-tree', '--no-commit-id', '--name-status', '-r', head, tip) !== 'A\tregistrations/verifier.json') throw new Stop('the verifier registration commit changes more than registrations/verifier.json', 3);
      verifier = parseRegistration(gitRaw('show', tip + ':registrations/verifier.json').toString('utf8'));
      verifierSource = 'commit ' + tip + ', signed by the Director key, on top of this relay commit';
    }
  }
  if (!verifier && !PLAN) throw new Stop(`BLOCKED - the verifier has not published its registration: branch ${S.verifierBranch}, one Director-signed commit on top of ${head} adding registrations/verifier.json (README)`, 3);
  if (verifier && verifier.node_id === sender.node_id) throw new Stop('the verifier registration names this node: the sender and the verifier are two nodes', 3);
  step('the verifier\'s registration', verifier ? 'OK' : 'NOT PUBLISHED YET', verifier ? `${verifier.node_id} key ${verifier.public_key} (${verifierSource})` : 'the install will stop here until it is');
  const nodes = verifier ? [sender, verifier] : [sender];

  // ---------------------------------------------------------------------------------------------- 3 the Director's record
  let record = null;
  if (flags.has('--without-director-record')) {
    step('the Director\'s record (AC-10 / S-11)', 'SKIPPED', 'by the founder\'s explicit option --without-director-record');
  } else {
    let tip = null;
    try {
      if (!PLAN) git('fetch', '--quiet', S.remote, '+refs/heads/' + S.directorBranch + ':refs/relay-install/director');
      tip = git('rev-parse', '--verify', '--quiet', 'refs/relay-install/director');
    } catch { tip = null; }
    if (tip) {
      const d = commitSigner(gitRaw('cat-file', 'commit', tip));
      if (!d.ok || d.fingerprint !== S.directorFingerprint) throw new Stop('the Director branch tip ' + tip + ' is not signed by the Director key', 3);
      let events = [];
      try { events = JSON.parse(gitRaw('show', tip + ':' + S.directorLedger).toString('utf8')).events ?? []; } catch { events = []; }
      if (events.some((e) => typeof e?.event === 'string' && e.event.includes(head))) record = tip;
    }
    if (!record && !PLAN) {
      throw new Stop(`BLOCKED - the Director's event log does not record the founder-approved change for relay commit ${head}. Installed before that record, the relay's objects are read as findings against every noticed candidate (AC-10 / S-11). The Director records it first; or run again with --without-director-record.`, 3);
    }
    step('the Director\'s record (AC-10 / S-11)', record ? 'OK' : 'NOT RECORDED YET', record ? 'the event log at ' + record + ' names this relay commit' : 'the install will stop here until it is');
  }

  // ------------------------------------------------------------------------------------------------------------- the plan
  const registryText = verifier ? renderRegistry(nodes) : null;
  const registration = verifier ? file('sql/010_register_nodes.template.sql').replace('<WORK NODE ID>', sender.node_id).replace('<WORK RELAY PUBLIC KEY>', sender.public_key)
    .replace('<HOME NODE ID>', verifier.node_id).replace('<HOME RELAY PUBLIC KEY>', verifier.public_key) : null;
  if (PLAN) {
    say();
    say('WHAT THE INSTALL CHANGES on project ' + S.project + ', and nothing else:');
    say('  schema    factory_relay, with what sql/001_artifact_relay_v0.sql creates in it      sha256 ' + manifest.find((m) => m.file === 'sql/001_artifact_relay_v0.sql').sha256);
    say('  function  public.factory_relay_rpc(jsonb), executable by service_role only        (same file)');
    say('  bucket    ' + BUCKET + ', private, 2 MiB per object                   sql/002_private_bucket.sql ' + manifest.find((m) => m.file === 'sql/002_private_bucket.sql').sha256);
    say('  rows      two registrations in factory_relay.nodes:');
    say(`              sender    ${sender.node_id}  key ${sender.public_key}`);
    say(`              verifier  ${verifier ? verifier.node_id + '  key ' + verifier.public_key : '<the node and key of the Director-signed registration>'}`);
    say(`  edge      function ${FUNCTION}, JWT verification OFF: index.ts ${manifest.find((m) => m.file === FUNCTION_DIR + '/index.ts').sha256}`);
    say(`                                                             relay.ts ${manifest.find((m) => m.file === FUNCTION_DIR + '/relay.ts').sha256}`);
    say(`                                                             registry.ts ${registryText ? sha256(registryText) + ' (generated from the two registrations)' : '<generated from the two registrations>'}`);
    say('  It creates no role, no extension, no secret and no storage policy, and it changes no existing object.');
    say('It reads: the pre-check and the post-check (read-only SQL), and the deployed function\'s own record. It never reads the project\'s API keys.');
    say('Undo: node relay/install.mjs --uninstall   (relay/install.ps1 -Uninstall)');
    say();
    say('ARTIFACT RELAY V0 PLAN: nothing was changed');
    return 0;
  }

  // -------------------------------------------------------------------------------------------- from here on: the project
  if (token.length < 20) throw new Stop('SUPABASE_ACCESS_TOKEN is not set: relay/install.ps1 asks for it without echo', 2);
  const receipt = { relay: 'artifact-relay/v0', project: S.project, commit: head, manifest_sha256: sha256(readFileSync(join(S.root, 'MANIFEST.sha256'))), registrations: nodes, verifier_registration: verifierSource,
    director_record: record ?? 'skipped by --without-director-record', registry_sha256: sha256(registryText), steps };
  const finish = (result, code) => {
    receipt.result = result; receipt.finished_at = new Date().toISOString();
    mkdirSync(relayHome(), { recursive: true });
    const out = join(relayHome(), 'install-receipt.json');
    writeFileSync(out, clean(JSON.stringify(receipt, null, 2)) + '\n');
    say();
    say('ARTIFACT RELAY V0 INSTALL: ' + result);
    say('receipt ' + out);
    return code;
  };
  try {
    const state = await readState();
    // 4 pre-check
    if (!state.installed && !state.wrapper) {
      const rows = (await query(file('sql/000_precheck.sql'))).filter((r) => !/^factory node /.test(r.line));
      const bad = rows.filter((r) => r.result !== 'ok');
      if (rows.length !== 8 || bad.length) throw new Stop('the pre-check is not all ok: ' + (bad.map((r) => r.line + ' - ' + r.result).join('; ') || rows.length + ' lines'));
      step('pre-check (read-only)', 'OK', '8 of 8');
    } else {
      step('pre-check (read-only)', 'ALREADY INSTALLED', 'the post-check below judges what is there');
    }
    // 5 the schema
    if (state.installed !== state.wrapper) throw new Stop('the relay is half installed (the schema and its wrapper are not both there): run the uninstall, then install again');
    if (!state.installed) { await query(file('sql/001_artifact_relay_v0.sql')); step('the schema, in one transaction', 'APPLIED', 'sql/001_artifact_relay_v0.sql'); }
    else step('the schema, in one transaction', 'ALREADY THERE');
    // 6 the bucket
    if (state.bucket === null) { await query(file('sql/002_private_bucket.sql')); step('the private bucket', 'APPLIED', BUCKET); }
    else if (state.bucket.public !== false) throw new Stop('the bucket ' + BUCKET + ' exists and is not private');
    else step('the private bucket', 'ALREADY THERE', 'private');
    // 7 the registrations
    const have = (await query(file('sql/021_registered.sql')))[0]?.nodes ?? [];
    // compared field by field: the database answers with its own order of fields
    const same = (list) => list.map((n) => n.relay_role + ' ' + n.node_id + ' ' + n.public_key).sort().join(' | ');
    if (have.length === 0) {
      const answers = await query(registration);
      step('register the two nodes', 'APPLIED', answers.map((r) => r.registered).join('; '));
    } else if (same(have) === same(nodes)) {
      step('register the two nodes', 'ALREADY THERE');
    } else {
      throw new Stop('other nodes or keys are registered than the two of this install: ' + have.map((n) => n.relay_role + ' ' + n.node_id).join(', ') + '. Deactivate them first (FOUNDER_STEP.md).');
    }
    // 8 post-check, after telling the API that there is a new function
    await query(`notify pgrst, 'reload schema'`);
    const post = (await query(file('sql/003_postcheck.sql'))).filter((r) => !/^registered /.test(r.line));
    const postBad = post.filter((r) => r.result !== 'ok');
    if (post.length !== 7 || postBad.length) throw new Stop('the post-check is not all ok: ' + (postBad.map((r) => r.line + ' - ' + r.result).join('; ') || post.length + ' lines'));
    step('post-check (read-only)', 'OK', '7 of 7');
    // 9 the function, with the same two registrations
    const staging = mkdtempSync(join(tmpdir(), 'relay-deploy-'));
    try {
      mkdirSync(join(staging, FUNCTION_DIR), { recursive: true });
      writeFileSync(join(staging, 'supabase', 'config.toml'), file('supabase/config.toml'));
      for (const f of ['index.ts', 'relay.ts']) writeFileSync(join(staging, FUNCTION_DIR, f), file(FUNCTION_DIR + '/' + f));
      writeFileSync(join(staging, FUNCTION_DIR, 'registry.ts'), registryText);
      const r = cli(['functions', 'deploy', FUNCTION, '--project-ref', S.project, '--no-verify-jwt', '--use-api', '--workdir', staging]);
      if (r.status !== 0) throw new Stop('the function was not deployed: ' + clean(((r.stderr || '') + (r.stdout || '')).trim().split('\n').slice(-4).join(' | ') || 'the deploy command could not be run'));
    } finally { rmSync(staging, { recursive: true, force: true }); }
    const deployed = await api('GET', `/v1/projects/${S.project}/functions/${FUNCTION}`);
    receipt.function = { slug: deployed.slug, status: deployed.status, version: deployed.version, verify_jwt: deployed.verify_jwt, updated_at: deployed.updated_at, ezbr_sha256: deployed.ezbr_sha256 };
    if (deployed.verify_jwt !== false) throw new Stop('the function is deployed with JWT verification ON: a node holds no project key and could not reach it');
    step('deploy the function', 'DEPLOYED', `JWT verification off; version ${deployed.version ?? '?'}; registry.ts ${sha256(registryText)}`);
    // 10 selfcheck, through the deployed function
    let last = null;
    for (let i = 0; i < 18; i++) {
      try { last = await call(cfg, 'selfcheck'); } catch (e) { last = { status: 0, body: { refused: e.message } }; }
      if (last.status === 200 && last.body.ok === true) break;
      await new Promise((r) => setTimeout(r, S.test ? 200 : 5000));
    }
    receipt.selfcheck = { status: last.status, ...last.body };
    if (!(last.status === 200 && last.body.ok === true && last.body.relay_role === 'sender' && last.body.bucket === 'private' && last.body.sender_registered && last.body.verifier_registered)) {
      throw new Stop(`the deployed function does not answer this node as it must: ${last.body.refused ?? 'no answer'}${last.body.detail ? ' (' + last.body.detail + ')' : ''} [${last.status}]`);
    }
    step('selfcheck from this node', 'OK', `REGISTERED ${last.body.node_id} as sender; bucket private; both nodes registered`);
    return finish('PASS', 0);
  } catch (e) {
    if (!(e instanceof Stop)) throw e;
    step('STOPPED', 'FAIL', clean(e.message));
    say('What the steps above APPLIED stays applied. Run the installer again once the cause is removed (it continues where it stopped), or remove everything with --uninstall.');
    return finish('FAIL', 1);
  }

  // ------------------------------------------------------------------------------------------------------------- helpers
  async function api(method, path, body) {
    let r;
    try {
      r = await fetch(S.api + path, { method, headers: { authorization: 'Bearer ' + token, ...(body ? { 'content-type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined, signal: AbortSignal.timeout(180000) });
    } catch (e) { throw new Stop('the Supabase management API could not be reached: ' + (e.cause?.code ?? e.name)); }
    const text = await r.text();
    if (r.status === 401 || r.status === 403) throw new Stop(`the access token was refused [${r.status}]: it must be allowed to run SQL and deploy functions on project ${S.project}`);
    let parsed = null;
    try { parsed = JSON.parse(text); } catch { /* not JSON */ }
    if (!r.ok) throw new Stop(`the project refused it [${r.status}]: ${clean(String(parsed?.message ?? text).slice(0, 400))}`);
    return parsed;
  }
  /** one SQL text, run as the database owner; the rows of its last statement */
  async function query(sql) {
    const v = await api('POST', `/v1/projects/${S.project}/database/query`, { query: sql });
    const rows = Array.isArray(v) ? v : Array.isArray(v?.result) ? v.result : Array.isArray(v?.rows) ? v.rows : Array.isArray(v?.data) ? v.data : null;
    if (rows === null) throw new Stop('the management API answered a statement in a shape this installer does not know (' + (v === null ? 'no JSON' : 'keys: ' + Object.keys(v).join(', ')) + ')');
    return rows;
  }
  async function readState() {
    const row = (await query(file('sql/020_state.sql')))[0];
    const state = typeof row?.state === 'string' ? JSON.parse(row.state) : row?.state;
    if (!state || typeof state.installed !== 'boolean') throw new Stop('the project did not answer the state question as expected');
    if (state.login !== 'postgres') throw new Stop('the management API runs SQL as ' + state.login + ', not as the database owner postgres');
    return state;
  }
  function cli(args) {
    const env = { ...process.env, SUPABASE_ACCESS_TOKEN: token };
    if (S.cli) return spawnSync(process.execPath, [S.cli, ...args], { env, encoding: 'utf8', timeout: 600000 });
    // the Supabase CLI, through the npx that ships with this Node (no shell, so no quoting to get wrong)
    const npx = join(dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npx-cli.js');
    if (existsSync(npx)) return spawnSync(process.execPath, [npx, '--yes', 'supabase@2', ...args], { env, encoding: 'utf8', timeout: 600000 });
    return spawnSync('npx', ['--yes', 'supabase@2', ...args], { env, encoding: 'utf8', timeout: 600000 });
  }

  async function uninstall() {
    if (token.length < 20) throw new Stop('SUPABASE_ACCESS_TOKEN is not set: relay/install.ps1 asks for it without echo', 2);
    try {
      const state = await readState();
      const objects = Number(state.bucket?.objects ?? 0);
      if (objects > 0 && !flags.has('--leave-bucket')) {
        throw new Stop(`the bucket still holds ${objects} object(s). The relay deletes an artifact's bytes when it expires; removing the relay now would leave them behind. Run again with --leave-bucket to remove the rest and keep the bucket for the dashboard.`);
      }
      const r = cli(['functions', 'delete', FUNCTION, '--project-ref', S.project]);
      const gone = r.status === 0 || /not found|404|does not exist/i.test((r.stderr || '') + (r.stdout || ''));
      if (!gone) throw new Stop('the function was not deleted: ' + clean(((r.stderr || '') + (r.stdout || '')).trim().split('\n').slice(-3).join(' | ')));
      step('delete the function', r.status === 0 ? 'DELETED' : 'WAS NOT THERE');
      if (state.bucket !== null && objects === 0) { await query(file('sql/098_remove_empty_bucket.sql')); step('remove the empty bucket', 'REMOVED'); }
      else step('remove the empty bucket', state.bucket === null ? 'WAS NOT THERE' : 'LEFT', state.bucket === null ? '' : objects + ' object(s) remain: delete the bucket in the dashboard');
      await query(file('sql/099_remove_artifact_relay_v0.sql'));
      step('drop the schema and the wrapper', 'REMOVED', 'sql/099_remove_artifact_relay_v0.sql');
      const after = await readState();
      if (after.installed || after.wrapper || (after.bucket !== null && objects === 0)) throw new Stop('something of the relay is still there');
      step('nothing of the relay is left', 'OK', after.bucket === null ? '' : 'except the bucket, as asked');
      say(); say('ARTIFACT RELAY V0 REMOVAL: PASS');
      return 0;
    } catch (e) {
      if (!(e instanceof Stop)) throw e;
      step('STOPPED', 'FAIL', clean(e.message));
      say(); say('ARTIFACT RELAY V0 REMOVAL: FAIL');
      return 1;
    }
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  try {
    process.exitCode = await main(process.argv.slice(2));
  } catch (e) {
    if (!(e instanceof Stop)) throw e;
    say(e.message);
    say();
    say('ARTIFACT RELAY V0 INSTALL: ' + (e.code === 3 ? 'BLOCKED' : 'STOPPED') + ' - nothing was changed');
    process.exitCode = e.code ?? 2;
  }
}
