window.SEM=window.SEM||{}; SEM.Modules=SEM.Modules||{};
SEM.Modules.autoTester = (()=>{
  const U=SEM.Utils;
  function row(t){ const cls=t.status==='PASS'?'green':t.status==='WARN'?'orange':'red'; return `<tr><td><b>${U.esc(t.name)}</b></td><td><span class="pill ${cls}">${U.esc(t.status)}</span></td><td>${U.esc(t.detail)}</td></tr>`; }
  return {
    render(){ const s=SEM.Store.get(); const last=(s.autoTestRuns||[])[0]; return `<div class="grid grid4"><div class="stat"><div class="label">Last Verdict</div><div class="num" style="font-size:24px">${U.esc(last?.verdict||'NOT RUN')}</div><span class="pill blue">autonomous</span></div><div class="stat"><div class="label">Passed</div><div class="num">${last?.passed||0}</div><span class="pill green">checks</span></div><div class="stat"><div class="label">Warnings</div><div class="num">${last?.warnings||0}</div><span class="pill orange">review</span></div><div class="stat"><div class="label">Failed</div><div class="num">${last?.failed||0}</div><span class="pill red">blockers</span></div></div><div class="grid grid2" style="margin-top:18px"><div class="card"><h3>Autonomous QA Agent</h3><p class="muted">This is the tester agent for the software factory. It runs non-destructive checks across UI modules, data collections, token controls, permissions and integration queues.</p><div class="actions"><button class="primary" id="runAutoTests">Run all tests</button><button class="ghost" id="createQaTickets">Create QA fix tickets</button></div><div id="autoTestOutput" style="margin-top:14px">${last?`<table class="table"><thead><tr><th>Test</th><th>Status</th><th>Detail</th></tr></thead><tbody>${last.tests.map(row).join('')}</tbody></table>`:'<p class="muted">No test run yet.</p>'}</div></div><div class="card"><h3>Test History</h3><div class="list">${(s.autoTestRuns||[]).slice(0,10).map(r=>`<div class="item"><div class="itemHeader"><b>${U.esc(r.verdict)}</b><span class="pill blue">${U.esc(r.source||'manual')}</span></div><p class="muted">${U.esc(r.createdAt)} · ${r.passed} pass · ${r.warnings} warn · ${r.failed} fail</p></div>`).join('')||'<p class="muted">No history.</p>'}</div></div></div>`; },
    afterRender(){
      U.$('#runAutoTests').onclick=()=>{ const r=SEM.AutoTest.runAll({source:'auto_tester_page'}); U.$('#autoTestOutput').innerHTML=`<table class="table"><thead><tr><th>Test</th><th>Status</th><th>Detail</th></tr></thead><tbody>${r.tests.map(row).join('')}</tbody></table>`; U.toast(`QA ${r.verdict}`); SEM.App.render(); };
      U.$('#createQaTickets').onclick=()=>{ const s=SEM.Store.get(); const last=(s.autoTestRuns||[])[0]||SEM.AutoTest.runAll({source:'auto_ticket'}); last.tests.filter(t=>t.status!=='PASS').forEach(t=>s.softwareTickets.unshift({id:U.uid('sw'),title:`Fix QA issue: ${t.name}`,module:'detected by AutoTester',status:'queued',ownerPersonId:'p_engineer',qaRequired:true,approvalRequired:false,description:t.detail,createdAt:U.now()})); SEM.Store.save(); U.toast('QA fix tickets created'); SEM.App.render(); };
    }
  };
})();
