window.SEM=window.SEM||{}; SEM.Modules=SEM.Modules||{};
SEM.Modules.qaLab = (()=>{
  const U=SEM.Utils;
  function pass(name, detail, severity='info'){return {name, detail, status:'PASS', severity};}
  function fail(name, detail, severity='high'){return {name, detail, status:'FAIL', severity};}
  function warn(name, detail, severity='medium'){return {name, detail, status:'WARN', severity};}
  function runSuite(){
    const s=SEM.Store.get(); const results=[]; const routes=['dashboard','mindmap','qaLab','architectureAudit','command','tokenControl','moduleRegistry','access','myWork','companies','people','kpiSalary','sales','documents','productInventory','dealDesk','proposalFactory','integrations','automationExplorer','productFactory','softwareFactory','projects','tasks','memory','approvals','agents','settings'];
    // UI / data health
    results.push(s.companies?.length>=1?pass('Company database seeded',`${s.companies.length} companies found`):fail('Company database seeded','No companies found'));
    results.push(s.people?.length>=1?pass('People database seeded',`${s.people.length} people found`):fail('People database seeded','No people found'));
    results.push(s.tasks?.length>=1?pass('Task queue seeded',`${s.tasks.length} tasks found`):warn('Task queue seeded','No tasks yet'));
    results.push(s.memories?.length>=1?pass('Memory database seeded',`${s.memories.length} memories found`):fail('Memory database seeded','No memories found'));
    results.push((s.documents||[]).length>=1?pass('Document library seeded',`${s.documents.length} document records found`):warn('Document library seeded','No document records yet'));
    results.push((s.productLines||[]).length>=1?pass('Product catalog seeded',`${s.productLines.length} product lines found`):fail('Product catalog seeded','No product lines found'));
    results.push((s.inventoryItems||[]).length>=1?pass('Inventory records seeded',`${s.inventoryItems.length} inventory records found`):warn('Inventory records seeded','No inventory records yet'));
    results.push(s.integrationSettings?.slack&&s.integrationSettings?.googleDrive?pass('Integration settings exist','Slack and Google Drive settings available'):fail('Integration settings exist','Missing connector settings'));
    results.push(Array.isArray(s.quotations)&&Array.isArray(s.proposals)&&Array.isArray(s.proposalTemplates)&&Array.isArray(s.proposalVersions)?pass('Proposal factory structures exist','Quotation, proposal, template, and version arrays available'):fail('Deal desk structures exist','Missing quote/proposal arrays'));
    routes.forEach(r=>{ const mod=SEM.Modules[r]; results.push(mod?.render?pass(`UI route: ${r}`,'Render function exists'):fail(`UI route: ${r}`,'Missing module render function')); });
    // permission tests
    const founder=s.users.find(u=>u.role==='founder'); const employee=s.users.find(u=>u.role==='employee'); const parent=s.companies.find(c=>c.id==='c_parent'); const person=s.people.find(p=>p.compensationMonthly>0) || s.people[0];
    results.push(SEM.Permissions.canSeeOwnership(founder)?pass('Founder can see ownership','Founder role passes ownership gate'):fail('Founder can see ownership','Founder cannot see ownership'));
    results.push(!SEM.Permissions.canSeeOwnership(employee)?pass('Employee cannot see ownership','Ownership hidden from employee role'):fail('Employee cannot see ownership','Employee can see ownership'));
    const safeParent=SEM.Permissions.safeCompany(employee,parent);
    results.push(!('parentEntityId' in safeParent)&&!('cashBalance' in safeParent)?pass('Employee company data sanitized','Parent/cash fields removed'):fail('Employee company data sanitized','Restricted company fields leaked'));
    const safePerson=SEM.Permissions.safePerson(employee,person);
    results.push(employee.personId===person.id || !('compensationMonthly' in safePerson)?pass('Salary visibility scoped','Other employee salary hidden'):fail('Salary visibility scoped','Other employee salary visible'));
    // AI/token architecture
    const cmd='Create OpenSpot sales campaign, social posts, chatbot questions and approval gates'; const ctx=SEM.ContextPack.build(cmd); const plan=SEM.TokenBudget.estimateCommand(cmd,{category:SEM.Pipeline.categoryOf(cmd), riskLevel:SEM.Pipeline.riskOf(cmd), contextPack:ctx});
    results.push(ctx.counts.totalRecords < 80?pass('Context pack is compact',`${ctx.counts.totalRecords} records in AI context`):warn('Context pack is compact',`${ctx.counts.totalRecords} records may be too high`));
    results.push(plan.totalTokens < s.settings.hardStopTokensPerCommand?pass('Token hard-stop respected',`${plan.totalTokens} estimated tokens`):fail('Token hard-stop respected',`${plan.totalTokens} exceeds hard stop`));
    results.push(plan.route!=='strong'?pass('Model router avoids strong model for normal command',`Route: ${plan.route}`):warn('Model router avoids strong model for normal command','Strong model selected'));
    const fallback=SEM.Pipeline.fallbackDecompose(cmd,ctx);
    results.push(fallback.tasks?.length>=3?pass('Task decomposition creates atomic tasks',`${fallback.tasks.length} tasks created in dry-run`):fail('Task decomposition creates atomic tasks','Too few tasks'));
    results.push(fallback.tasks.every(t=>Array.isArray(t.acceptanceCriteria)&&t.acceptanceCriteria.length>0)?pass('Tasks include acceptance criteria','Every dry-run task has criteria'):fail('Tasks include acceptance criteria','Some tasks missing criteria'));
    results.push(fallback.tasks.some(t=>t.approvalRequired)?pass('Approval gates triggered','External/social tasks require approval'):fail('Approval gates triggered','No approval gate created for external work'));
    // module split tests
    const moduleFiles=['js/core/tokenBudget.js','js/ai/contextPack.js','js/ai/pipeline.js','js/modules/sales.js','js/modules/dealDesk.js','js/modules/proposalFactory.js','js/modules/productFactory.js','js/modules/softwareFactory.js','js/modules/mindmap.js','js/modules/qaLab.js'];
    results.push(moduleFiles.length>=8?pass('Module split defined',`${moduleFiles.length} critical modules listed`):fail('Module split defined','Too few modules'));
    const failures=results.filter(r=>r.status==='FAIL').length, warnings=results.filter(r=>r.status==='WARN').length;
    const score=Math.max(0, Math.round(100 - failures*12 - warnings*4));
    const verdict=failures===0 && warnings<=3 ? 'QA PASS — ready for controlled internal pilot after RLS/backend setup' : failures===0 ? 'QA PASS WITH WARNINGS — fix medium issues before pilot' : 'NO-GO — fix failed tests before production pilot';
    return {id:U.uid('qa'), createdAt:U.now(), score, verdict, failures, warnings, results};
  }
  function renderResults(run){ if(!run) return '<p class="muted">Run QA to generate report.</p>'; const klass=run.failures?'red':run.warnings?'orange':'green'; return `<div class="item"><div class="itemHeader"><div><b>${U.esc(run.verdict)}</b><p class="muted">${U.esc(run.createdAt)} · Score ${run.score}/100</p></div><span class="pill ${klass}">${run.failures} fail · ${run.warnings} warn</span></div></div><table class="table"><thead><tr><th>Status</th><th>Test</th><th>Evidence</th><th>Severity</th></tr></thead><tbody>${run.results.map(r=>`<tr><td>${U.statusPill(r.status.toLowerCase())}</td><td><b>${U.esc(r.name)}</b></td><td>${U.esc(r.detail)}</td><td>${U.esc(r.severity)}</td></tr>`).join('')}</tbody></table>`; }
  return { render(){ const last=SEM.Store.get().qaRuns?.[0]; return `<div class="grid grid2"><div class="card"><div class="sectionTitle"><div><h3>QA / QC Lab</h3><p class="muted">CEO simulation test before production pilot: UI, access, token safety, task decomposition, approval gates.</p></div><button class="primary" id="runQa">Run non-destructive QA</button></div><div class="grid grid3"><div class="stat"><div class="label">Last QA score</div><div class="num">${last?last.score:'—'}</div><span class="pill blue">0-100</span></div><div class="stat"><div class="label">Failures</div><div class="num">${last?last.failures:'—'}</div><span class="pill red">must fix</span></div><div class="stat"><div class="label">Warnings</div><div class="num">${last?last.warnings:'—'}</div><span class="pill orange">review</span></div></div><div id="qaOut" style="margin-top:16px">${renderResults(last)}</div></div><div class="card"><h3>Manual CEO Test Script</h3><ol><li>Login as Founder and confirm all holdings, tasks, approvals, AI agents and KPI/salary pages are visible.</li><li>Switch to Employee and confirm ownership, cash, parent structure and other salaries are hidden.</li><li>Open Mindmap and confirm it uses real data nodes and permission-scoped view.</li><li>Run Founder Command in Estimate mode and confirm context pack is small.</li><li>Run a sales command and confirm external/social outputs go to approval.</li><li>Open Module Registry and confirm change prompts are patch-only.</li><li>Upload a text document and confirm memory snippets are created.</li><li>Create a product line, inventory record, and quotation in Meeting Deal Desk.</li><li>Open Proposal Factory, generate a proposal package, export client HTML and internal margin report.</li><li>Queue Slack and Drive actions without actually sending externally.</li></ol><div class="item"><b>Production pilot gate</b><p class="muted">Do not pilot with employees until QA PASS, Supabase RLS, backend API keys, audit logs and role-scoped table queries are verified.</p></div></div></div>`; }, afterRender(){ U.$('#runQa').onclick=()=>{ const run=runSuite(); const s=SEM.Store.get(); s.qaRuns=s.qaRuns||[]; s.qaRuns.unshift(run); SEM.Store.save(); U.$('#qaOut').innerHTML=renderResults(run); U.toast('QA completed'); SEM.App.render(); }; }};
})();
